import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class IconMapper {
  static final Map<String, IconData> _nameToIcon = {
    'Fast Food': Icons.fastfood,
    'Burger': FontAwesomeIcons.burger,
    'Restaurant': FontAwesomeIcons.utensils,
    'Vegetables': FontAwesomeIcons.carrot,
    'Seafood': FontAwesomeIcons.fish,
    'Fruits': FontAwesomeIcons.appleWhole,
    'Beverages': FontAwesomeIcons.beerMugEmpty,
    'Groceries': FontAwesomeIcons.shoppingCart,
    'Clothing': FontAwesomeIcons.shoppingBag,
    'Rent': FontAwesomeIcons.house,
    'Electricity': FontAwesomeIcons.plug,
    'Water': FontAwesomeIcons.shower,
    'Internet': FontAwesomeIcons.wifi,
    'Insurance': FontAwesomeIcons.shieldHalved,
    'Utilities': FontAwesomeIcons.bolt,
    'TV': FontAwesomeIcons.tv,
    'Laptop': FontAwesomeIcons.laptop,
    'Mobile': FontAwesomeIcons.mobile,
    'Camera': FontAwesomeIcons.camera,
    'Watches': FontAwesomeIcons.clock,
    'Furniture': FontAwesomeIcons.couch,
    'Bedding': FontAwesomeIcons.bed,
    'Repair': FontAwesomeIcons.tools,
    'Car': FontAwesomeIcons.car,
    'Fuel': FontAwesomeIcons.gasPump,
    'Public Transport': FontAwesomeIcons.bus,
    'Flights': FontAwesomeIcons.plane,
    'Subway': FontAwesomeIcons.trainSubway,
    'Taxi': FontAwesomeIcons.taxi,
    'Hotel': FontAwesomeIcons.hotel,
    'Nature': FontAwesomeIcons.tree,
    'Garden': FontAwesomeIcons.seedling,
    'Pet - Cat': FontAwesomeIcons.cat,
    'Pet - Dog': FontAwesomeIcons.dog,
    'Pet Care': FontAwesomeIcons.paw,
    'Medical': FontAwesomeIcons.stethoscope,
    'Medicine': FontAwesomeIcons.pills,
    'Hospital': FontAwesomeIcons.hospital,
    'Health Insurance': FontAwesomeIcons.heartbeat,
    'Books': FontAwesomeIcons.book,
    'Education': FontAwesomeIcons.graduationCap,
    'School Fees': FontAwesomeIcons.school,
    'Work': FontAwesomeIcons.briefcase,
    'Salary': FontAwesomeIcons.moneyBill,
    'Saving': FontAwesomeIcons.piggyBank,
    'Investment': FontAwesomeIcons.coins,
    'Loan Payment': FontAwesomeIcons.handHoldingUsd,
    'Donation': FontAwesomeIcons.handHoldingHeart,
    'Gifts': FontAwesomeIcons.gift,
    'Fashion': FontAwesomeIcons.tshirt,
    'Cosmetics': FontAwesomeIcons.brush,
    'Salon': FontAwesomeIcons.cut,
    'Movie': FontAwesomeIcons.ticket,
    'Games': FontAwesomeIcons.gamepad,
    'Music': FontAwesomeIcons.music,
    'Art': FontAwesomeIcons.paintBrush,
    'Outdoor': FontAwesomeIcons.hiking,
    'Gym': FontAwesomeIcons.dumbbell,
    'Sports': FontAwesomeIcons.basketball,
    'Camping': FontAwesomeIcons.campground,
    'Vacation': FontAwesomeIcons.planeDeparture,
    'Adventure': FontAwesomeIcons.mountain,
    'Religion': FontAwesomeIcons.cross,
    'Solar Energy': FontAwesomeIcons.sun,
    'Nightlife': FontAwesomeIcons.moon,
    'Wallet': FontAwesomeIcons.wallet,
    'Cash': FontAwesomeIcons.cashRegister,
    'Stocks': FontAwesomeIcons.chartLine,
    'Statistics': FontAwesomeIcons.chartPie,
    'Exchange': FontAwesomeIcons.exchangeAlt,
    'Business Trip': FontAwesomeIcons.suitcase,
    'Security': FontAwesomeIcons.fingerprint,
    'Cleaning': FontAwesomeIcons.handSparkles,
    'Hygiene': FontAwesomeIcons.soap,
    'Waste': FontAwesomeIcons.trash,
    'Achievements': FontAwesomeIcons.trophy,
    'Alcohol': FontAwesomeIcons.wineGlass,
    'Fun': FontAwesomeIcons.smileBeam,
    'Social': FontAwesomeIcons.userFriends,
    'Events': FontAwesomeIcons.calendar,
    'City Fee': FontAwesomeIcons.treeCity,
    'Boat': FontAwesomeIcons.anchor,
    'Cooling': FontAwesomeIcons.fan,
    'Heating': FontAwesomeIcons.fire,
    'Subscriptions': FontAwesomeIcons.lock,
    'Keys': FontAwesomeIcons.key,
    'Maps': FontAwesomeIcons.mapMarkedAlt,
    'Luxury': FontAwesomeIcons.gem,
    'Unexpected': FontAwesomeIcons.exclamation,
    'Mortgage': FontAwesomeIcons.building,
    'Online Services': FontAwesomeIcons.globe,
    'Eco Fee': FontAwesomeIcons.seedling,
    'Winter': FontAwesomeIcons.snowflake,
    'Plumbing': FontAwesomeIcons.faucetDrip,
    'Housekeeping': FontAwesomeIcons.broom,
    'Finance': FontAwesomeIcons.chartBar,
    'Postage': FontAwesomeIcons.envelopeOpenText,
    'Freelance': FontAwesomeIcons.handshake,
    'Delivery': FontAwesomeIcons.box,
  };

  static final Map<IconData, String> _iconToName = {
    for (var entry in _nameToIcon.entries) entry.value: entry.key,
  };

  static IconData? getIcon(String name) => _nameToIcon[name];

  static String? getName(IconData icon) => _iconToName[icon];
}
